#!/usr/bin/ruby
#Test address database, particularly logic surrounding the primary record mechanism
require 'wyseman'
require 'wyseman/db'

DatabaseName	= File.read(File.join(File.dirname(__FILE__), 'DBNAME')).strip
db = Wyseman::DB.new({dbname: DatabaseName})

#Delete any test users other than admin
res = db.doDelete('base.ent', Hash['id',100])

#Load in our sample user
baseSql= %Q{
	INSERT INTO base.ent
		(id, ent_type, ent_name, fir_name, mid_name, pref_name, title, gender, marital, ent_cmt, born_date, username, database, ent_inact, inside, country, tax_id, bank, proxy)
	 VALUES	(100, 'o', 'Ahoy Chips', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2017-01-01', NULL, false, false, true, 'US', '234-56-7890', NULL, NULL);
	
	INSERT INTO base.addr
		(addr_ent, addr_seq, addr_spec, addr_type, addr_prim, addr_cmt, addr_inact, city, state, pcode, country) 
	 VALUES (100, 1, '2345 Corporate Way', 'ship', true, 'Headquarters', false, 'Bigtown', 'NY', '12345', 'US')
	      , (100, 2, '5432 Back Way', 'ship', false, 'Alternate Plant', false, 'Littletown', 'NM', '23456', 'US')
	      , (100, 3, '6543 Side Way', 'ship', false, 'Job Site', false, 'Sometown', 'CA', '34567', 'US')
	      ,	(100, 4, 'PO Box 4567', 'bill', true, 'Mailing address', false, 'Bigtown', 'Ny', '12345-4567', 'US');
}
res = db.exec(baseSql)
#printf("Result:%s\n", res)

res = db.doSelect('*', 'base.ent', {id:100})
#printf("Tuples:%s id:%s\n", res.ntuples, res[0]['id'])
raise 'Failure to insert test data' if res.ntuples != 1 or res[0]['id'] != '100'

def comSelect(db)
  db.doSelect('addr_seq,addr_type,addr_cmt,addr_prim', 'base.addr_v', {addr_ent:100, addr_type:'ship', addr_prim:true})
end

#Imported with correct primary record
res = comSelect(db)
#printf("Ship primary:%s\n", res[0])
raise 'Wrong phone record primary' if res.ntuples != 1 or res[0]['addr_seq'] != '1'

#Can change primary record
res = db.doUpdate('base.addr_v', {addr_prim:'true'}, {addr_ent:100, addr_seq:2})
res = comSelect(db)
#printf("Ship primary:%s\n", res[0])
raise "Couldn't set new ship record primary" if res.ntuples != 1 or res[0]['addr_seq'] != '2'

#Setting inactive moves primary away from our record
res = db.doUpdate('base.addr_v', {addr_inact:'true'}, "addr_ent = 100 and addr_type = 'ship' and addr_seq < 3")
res = comSelect(db)
#printf("Phone primary:%s\n", res[0])
raise "Primary records should resolve to 3" if res.ntuples != 1 or res[0]['addr_seq'] != '3'

#Attempt to clear primary fails
res = db.doUpdate('base.addr_v', {addr_inact:'false'}, "addr_ent = 100")
res = db.doUpdate('base.addr_v', {addr_prim:'false'}, "addr_ent = 100 and addr_seq = 3")
res = comSelect(db)
#printf("Phone primary:%s\n", res[0])
raise "Primary records should still be 3" if res.ntuples != 1 or res[0]['addr_seq'] != '3'

