#!/bin/bash
#Initialize a sample database and run all automated tests
#TODO:
#- Write tests for more than just base
#- 

export RUBYOPT="-I $(pwd)/../../wyseman/lib"	#Needed for ruby scripts below
schemadir="../schema"
dbname=$(cat ./DBNAME)
dbuser=$(cat ./DBUSER)
logfname="/var/tmp/wyselib-test.log"
rm -f ${logfname}; touch $logfname
echo "Testing with Database: $dbname, Logging to: ${logfname}"

dropdb -U $dbuser $dbname 2>/dev/null
createdb -U $dbuser $dbname >>$logfname

wyseman --dbname=$dbname --user=${dbuser} ${schemadir}/*.wms ${schemadir}/base/*.wms >>$logfname
wyseman --dbname=$dbname --user=${dbuser} ${schemadir}/*.wmt ${schemadir}/base/*.wmt >>$logfname
wyseman --dbname=$dbname --user=${dbuser} ${schemadir}/base/*.wmd >>$logfname
wyseman --dbname=$dbname --user=${dbuser} ${schemadir}/base/*.wmi >>$logfname

./test_addr
./test_comm
./test_lang

echo -n "Ready to drop database: $dbname? "; read ans
if [ $ans == "y" -o $ans == "Y" ]; then
  dropdb -U $dbuser $dbname
fi
