#This file is automatically generated by wmmkpkg.

package ifneeded wyselib 0.20 [list set wyselib_library $dir]\n[list source [file join $dir init.tcl]]\n[list tclPkgSetup $dir wyselib 0.20 {
-n     {acct.tcl	source {
-n ::acct::cat_menu 
-n ::acct::acct_menu 
-n ::acct::meth_menu 
-n ::acct::clos_menu 
}}
-n     {base.tcl	source {
-n ::base::build 
-n ::base::priv_has 
-n ::base::priv_run 
-n ::base::priv_check 
-n ::base::priv_alarm 
-n ::base::priv_me 
-n ::base::user_eid 
-n ::base::user_name 
-n ::base::user_username 
-n ::base::menu_parm 
-n ::base::build_priv 
-n ::base::build_comm 
-n ::base::build_addr 
}}
-n     {empl.tcl	source {
}}
-n     {pdoc.tcl	source {
-n ::pdoc::pdoc_menu 
-n ::pdoc::open_build 
-n ::pdoc::logmenu 
-n ::pdoc::new 
}}
-n     {prod.tcl	source {
-n ::prod::build 
-n ::prod::proc_build 
-n ::prod::edit_build 
-n ::prod::parm_edit 
-n ::prod::oper_menu 
-n ::prod::type_menu 
-n ::prod::unit_menu 
-n ::prod::dtyp_menu 
-n ::prod::# 
-n ::prod::base_price 
-n ::prod::parm_edit 
-n ::prod::norm_parms 
-n ::prod::spec_price 
-n ::prod::cfig 
-n ::prod::edit_parms 
-n ::prod::split_part 
-n ::prod::mtr_schedule 
-n ::prod::mtr_by_part 
-n ::prod::time_history 
}}
-n     {proj.tcl	source {
-n ::proj::where_fam 
-n ::proj::ptyp_menu 
-n ::proj::proj_menu 
}}
-n     {tran.tcl	source {
-n ::tran::tran_menu 
}}
-e }]
