#This file is automatically generated by wmmkpkg.

package ifneeded wyselib 0.10 [list set wyselib_library $dir]\n[list source [file join $dir init.tcl]]\n[list tclPkgSetup $dir wyselib 0.10 {
    {acct.tcl	source {::acct::cat_menu ::acct::acct_menu ::acct::meth_menu ::acct::clos_menu }}
    {base.tcl	source {::base::build ::base::priv_has ::base::priv_run ::base::priv_check ::base::priv_alarm ::base::priv_me ::base::user_eid ::base::user_name ::base::user_username ::base::menu_parm }}
    {empl.tcl	source {::empl::build }}
    {pdoc.tcl	source {::pdoc::pdoc_menu ::pdoc::edit_build ::pdoc::logmenu ::pdoc::new }}
    {prod.tcl	source {::prod::build ::prod::proc_build ::prod::edit_build ::prod::parm_edit ::prod::# ::prod::base_price ::prod::parm_edit ::prod::norm_parms ::prod::spec_price ::prod::cfig ::prod::edit_parms ::prod::split_part ::prod::mtr_schedule ::prod::mtr_by_part ::prod::time_history }}
    {proj.tcl	source {::proj::where_fam ::proj::ptyp_menu ::proj::proj_menu }}
    {tran.tcl	source {::tran::tran_menu }}
}]
